### ISSUE TITLE
很棒的工具

### ISSUE THREAD

**Issue by able9527** [whwlsfb/SpringSpider#1]
师傅请教下，魔改添加其他目录是在哪添加，我添加完编译bp加载报错
![image](https://user-images.githubusercontent.com/59350511/197710251-dbdd7d3e-7df2-4797-9f66-d0cbf8f86cc8.png)
![image](https://user-images.githubusercontent.com/59350511/197710371-8144d97c-add0-4317-8f01-f6a3c8dfcf04.png)

**Comment by whwlsfb** [comment]
还有这个位置，并且还要添加页面检查相关的逻辑，因为不是简单 StatusCode == 200就算检测到的。
https://github.com/whwlsfb/SpringSpider/blob/fb9de43704e5a40a785f470fa598122df5d23542/src/main/java/burp/scanner/sub/SpringActuator.java#L16-L59

**Comment by whwlsfb** [comment]
而且建议不要添加heapdump的检查，这个文件一般比较庞大，不适合用在扫描场景

**Comment by able9527** [comment]
嗯嗯，我试着改下，感谢师傅
